### ISSUE TITLE
Add column that states the year to ggd_weekly_tests_following_notification_CM.csv

### ISSUE THREAD

**Issue by henriterhofte** [minvws/nl-covid19-notification-app-statistics#3]
### Describe the bug, issue or concern

Please add a column stating the year in https://github.com/minvws/nl-covid19-notification-app-statistics/blob/main/statistics/ggd_weekly_tests_following_notification_CM.csv 
Without such a colum, sorting and other ways to process weeks (e.g. into dates, to align it with other data) is hard.

### To Reproduce
N/A

### Expected behavior
See screenshot for example how the csv should look after importing to Excel (including year column)

### Screenshots
![image](https://user-images.githubusercontent.com/59959432/105350314-3f289b00-5beb-11eb-866f-ee50ba6d2ad4.png)

**Desktop (please complete the following information):**
 N/A
**Smartphone (please complete the following information):**
N/A

### Additional context
N/A

### Governance
- [x ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by skos001** [comment]
@henriterhofte the year column has been added 🙂 

Please let us known whether this new column meets your needs, in which case we will close this issue.

**Comment by henriterhofte** [comment]
Suits me fin, thanks.
