### ISSUE TITLE
Either remove last zero in percentages, OR calculate this digit collrectly in ggd_weekly_tests_following_notification_CM.csv

### ISSUE THREAD

**Issue by henriterhofte** [minvws/nl-covid19-notification-app-statistics#4]
### Describe the bug, issue or concern

The last digit in the various columns with percentages is wrong; in ggd_weekly_tests_following_notification_CM.csv. Either remove last zero in percentages, OR calculate this digit collrectly 

### To Reproduce
Take a random percentage and calculate it yourself based on tehe numbers provided

### Expected behavior
See screenshot below (only shows one of the three % columns); the calculated column shows the calculated percentages properly calculated and rounded to 2 decimals.

### Screenshots
![image](https://user-images.githubusercontent.com/59959432/105349960-bc9fdb80-5bea-11eb-9903-2588900a883e.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

### Additional context
N/A

### Governance
- [ x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by skos001** [comment]
Thanks for the feedback @henriterhofte!

The original data was delivered rounded to 1 decimal, but ended up erroneously rounded to 2 decimals here. This has been corrected to round to 1 decimal again. Can you please check to verify it now behaves as you would expect?

**Comment by henriterhofte** [comment]
Works as expected now, thanks.
