### ISSUE TITLE
App is discontinued, maar geeft melding als Bluetooth uit staat

### ISSUE THREAD

**Issue by Stefanie-B** [minvws/nl-covid19-notification-app-statistics#6]
### Describe the bug, issue or concern

Ik krijg het rode symbooltje dat ik geen contactmeldingen krijg als ik BT uitzet. Dit is niet nodig, omdat de app sowieso geen meldingen meer geeft. 

### To Reproduce
Bluetooth uitzetten.

### Expected behavior
Niks.

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s9
 - OS: Android 10
 - Version 2.5.6

### Additional context
Is handig om de app te houden voor als het weer slechter gaat.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by lpappalettera** [comment]
@Stefanie-B Thanks for reporting this. We are aware and have a fix ready. You can expect an app update in the upcoming days.

**Comment by lpappalettera** [comment]
Issue should be fixed in version 2.5.8. Took us a little bit longer than expected because of the reviewing process of Google Play store.
